spring:
  jpa:
    database: postgresql

tenantList:
  - id: tenantId1
    dataSource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql:db1
      username: postgres
      password: password
  - id: tenantId2
    dataSource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql:db2
      username: postgres
      password: password
