spring:
   jpa:
    database: postgresql

tenant:
  dataSourceMap:
    tenantId1: "driver;org.postgresql.Driver, url;jdbc:postgresql:db1, username;postgres, password;password"
    tenantId2: "driver;org.postgresql.Driver, url;jdbc:postgresql:db2, username;postgres, password;password"